# Server configuration
db_path: ./vault0.db
port: 8080
ui_path: ./ui/dist
migrations_path: ./migrations
db_encryption_key: ${DB_ENCRYPTION_KEY}  # No default for security-sensitive values
smart_contracts_path: ./contracts/artifacts
key_store_type: db

# Logging configuration
log:
  level: info
  format: console
  output_path: ""  # Empty means stdout
  request_logging: true
  sql_logging: false

# Blockchain configurations
blockchains:
  ethereum:
    rpc_url: https://ethereum-rpc.publicnode.com
    chain_id: 1
    default_gas_price: 20
    default_gas_limit: 21000
    explorer_url: https://etherscan.io
    explorer_api_key: ${ETHEREUM_EXPLORER_API_KEY}  # Keep as env var for security

  polygon:
    rpc_url: https://polygon-rpc.com
    chain_id: 137
    default_gas_price: 30
    default_gas_limit: 21000
    explorer_url: https://polygonscan.com
    explorer_api_key: ${POLYGON_EXPLORER_API_KEY}  # Keep as env var for security

  base:
    rpc_url: https://mainnet.base.org
    chain_id: 8453
    default_gas_price: 10
    default_gas_limit: 21000
    explorer_url: https://basescan.org
    explorer_api_key: ${BASE_EXPLORER_API_KEY}  # Keep as env var for security

# Token configurations
tokens:
  ethereum:
    - symbol: ETH
      type: native
      chain_type: ethereum
      address: "0x0000000000000000000000000000000000000000"
      decimals: 18
    - symbol: WBTC
      type: erc20
      chain_type: ethereum
      address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
      decimals: 8
    - symbol: WETH
      type: erc20
      chain_type: ethereum
      address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      decimals: 18
    - symbol: USDC
      type: erc20
      chain_type: ethereum
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      decimals: 6
    - symbol: USDT
      type: erc20
      chain_type: ethereum
      address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      decimals: 6
    - symbol: DAI
      type: erc20
      chain_type: ethereum
      address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
      decimals: 18
    - symbol: LINK
      type: erc20
      chain_type: ethereum
      address: "0x514910771AF9Ca656af840dff83E8264EcF986CA"
      decimals: 18
    - symbol: UNI
      type: erc20
      chain_type: ethereum
      address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"
      decimals: 18
    - symbol: MATIC
      type: erc20
      chain_type: ethereum
      address: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0"
      decimals: 18
  
  polygon:
    - symbol: MATIC
      type: native
      chain_type: polygon
      address: "0x0000000000000000000000000000000000000000"
      decimals: 18
    - symbol: WMATIC
      type: erc20
      chain_type: polygon
      address: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
      decimals: 18
    - symbol: WBTC
      type: erc20
      chain_type: polygon
      address: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
      decimals: 8
    - symbol: WETH
      type: erc20
      chain_type: polygon
      address: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
      decimals: 18
    - symbol: USDC
      type: erc20
      chain_type: polygon
      address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
      decimals: 6
    - symbol: USDT
      type: erc20
      chain_type: polygon
      address: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
      decimals: 6
    - symbol: DAI
      type: erc20
      chain_type: polygon
      address: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
      decimals: 18
    - symbol: LINK
      type: erc20
      chain_type: polygon
      address: "0xb0897686c545045aFc77CF20eC7A532E3120E0F1"
      decimals: 18
    - symbol: UNI
      type: erc20
      chain_type: polygon
      address: "0xb33EaAd8d922B1083446DC23f610c2567fB5180f"
      decimals: 18
  
  base:
    - symbol: ETH
      type: native
      chain_type: base
      address: "0x0000000000000000000000000000000000000000"
      decimals: 18
    - symbol: WETH
      type: erc20
      chain_type: base
      address: "0x4200000000000000000000000000000000000006"
      decimals: 18
    - symbol: USDC
      type: erc20
      chain_type: base
      address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
      decimals: 6
    - symbol: DAI
      type: erc20
      chain_type: base
      address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
      decimals: 18
    - symbol: USDT
      type: erc20
      chain_type: base
      address: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"
      decimals: 6
    - symbol: WBTC
      type: ERC20
      chain_type: BASE
      address: "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
      decimals: 8
