# Server configuration
db_path: ${DB_PATH:-./vault0.db}
port: ${SERVER_PORT:-8080}
ui_path: ${UI_PATH:-./ui/dist}
migrations_path: ${MIGRATIONS_PATH:-./migrations}
db_encryption_key: ${DB_ENCRYPTION_KEY}  # No default for security-sensitive values
smart_contracts_path: ${SMART_CONTRACTS_PATH:-./contracts/artifacts}
key_store_type: ${KEYSTORE_TYPE:-db}

# Logging configuration
log:
  level: ${LOG_LEVEL:-info}
  format: ${LOG_FORMAT:-console}
  output_path: ${LOG_OUTPUT_PATH:-}  # Empty default means stdout
  request_logging: ${LOG_REQUESTS:-true}
  sql_logging: ${LOG_SQL:-false}

# Token configurations
tokens:
  ethereum:
    - name: ETH
      type: native
      chain_type: ethereum
      decimals: 18
    - name: USDC
      type: erc20
      chain_type: ethereum
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      decimals: 6
    - name: USDT
      type: erc20
      chain_type: ethereum
      address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      decimals: 6
    - name: DAI
      type: erc20
      chain_type: ethereum
      address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
      decimals: 18
  
  polygon:
    - name: MATIC
      type: native
      chain_type: polygon
      decimals: 18
    - name: USDC
      type: erc20
      chain_type: polygon
      address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
      decimals: 6
    - name: USDT
      type: erc20
      chain_type: polygon
      address: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
      decimals: 6
    - name: DAI
      type: erc20
      chain_type: polygon
      address: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
      decimals: 18
  
  base:
    - name: ETH
      type: native
      chain_type: base
      decimals: 18
    - name: USDC
      type: erc20
      chain_type: base
      address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
      decimals: 6
    - name: DAI
      type: erc20
      chain_type: base
      address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
      decimals: 18

# Blockchain configurations
blockchains:
  ethereum:
    rpc_url: ${ETHEREUM_RPC_URL:-https://ethereum-rpc.publicnode.com}
    chain_id: ${ETHEREUM_CHAIN_ID:-1}
    default_gas_price: ${ETHEREUM_GAS_PRICE:-20}
    default_gas_limit: ${ETHEREUM_GAS_LIMIT:-21000}
    explorer_url: ${ETHEREUM_EXPLORER_URL:-https://etherscan.io}
    explorer_api_key: ${ETHEREUM_EXPLORER_API_KEY:-}

  polygon:
    rpc_url: ${POLYGON_RPC_URL:-https://polygon-rpc.com}
    chain_id: ${POLYGON_CHAIN_ID:-137}
    default_gas_price: ${POLYGON_GAS_PRICE:-30}
    default_gas_limit: ${POLYGON_GAS_LIMIT:-21000}
    explorer_url: ${POLYGON_EXPLORER_URL:-https://polygonscan.com}
    explorer_api_key: ${POLYGON_EXPLORER_API_KEY:-}

  base:
    rpc_url: ${BASE_RPC_URL:-https://mainnet.base.org}
    chain_id: ${BASE_CHAIN_ID:-8453}
    default_gas_price: ${BASE_GAS_PRICE:-10}
    default_gas_limit: ${BASE_GAS_LIMIT:-21000}
    explorer_url: ${BASE_EXPLORER_URL:-https://basescan.org}
    explorer_api_key: ${BASE_EXPLORER_API_KEY:-} 