# Server configuration
db_path: ./vault0.db
port: 8080
ui_path: ./ui/dist
migrations_path: ./migrations
db_encryption_key: ${DB_ENCRYPTION_KEY}  # No default for security-sensitive values
smart_contracts_path: ./contracts/artifacts
key_store_type: db

# Snowflake ID generation configuration
snowflake:
  data_center_id: 1
  machine_id: 1

# Logging configuration
log:
  level: info
  format: console
  output_path: ""  # Empty means stdout
  request_logging: true
  sql_logging: false

# Blockchain configurations
blockchains:
  ethereum:
    rpc_url: https://ethereum-rpc.publicnode.com
    chain_id: 1
    default_gas_price: 20
    default_gas_limit: 21000
    explorer_url: https://etherscan.io
    explorer_api_url: https://api.etherscan.io/api
    explorer_api_key: ${ETHEREUM_EXPLORER_API_KEY}  # Keep as env var for security

  polygon:
    rpc_url: https://polygon-bor-rpc.publicnode.com
    chain_id: 137
    default_gas_price: 30
    default_gas_limit: 21000
    explorer_url: https://polygonscan.com
    explorer_api_url: https://api.polygonscan.com/api
    explorer_api_key: ${POLYGON_EXPLORER_API_KEY}  # Keep as env var for security

  base:
    rpc_url: https://base-rpc.publicnode.com
    chain_id: 8453
    default_gas_price: 10
    default_gas_limit: 21000
    explorer_url: https://basescan.org
    explorer_api_url: https://api.basescan.org/api
    explorer_api_key: ${BASE_EXPLORER_API_KEY}  # Keep as env var for security
