name: Smart Contract CI

on:
  push:
    branches: [ main ]    
  pull_request:
    branches: [ main ]    

jobs:
  test:
    name: Compile and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './contracts/package-lock.json'

      - name: Install dependencies
        run: cd contracts && npm ci

      - name: Create test environment file
        run: |
          cd contracts
          cat > .env.test << EOL
          # Test Private Key (Hardhat test account)
          PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

          # Test Addresses (Hardhat test accounts)
          CLIENT_ADDRESS=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
          RECOVERY_ADDRESS=0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
          EOL

      - name: Compile contracts
        run: cd contracts && npm run compile

      - name: Run tests
        run: cd contracts && npm run test

      - name: Run coverage
        run: cd contracts && npm run test:coverage

